//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: ./cloudstack/ExternalDeviceService.go

// Package cloudstack is a generated GoMock package.
package cloudstack

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockExternalDeviceServiceIface is a mock of ExternalDeviceServiceIface interface.
type MockExternalDeviceServiceIface struct {
	ctrl     *gomock.Controller
	recorder *MockExternalDeviceServiceIfaceMockRecorder
}

// MockExternalDeviceServiceIfaceMockRecorder is the mock recorder for MockExternalDeviceServiceIface.
type MockExternalDeviceServiceIfaceMockRecorder struct {
	mock *MockExternalDeviceServiceIface
}

// NewMockExternalDeviceServiceIface creates a new mock instance.
func NewMockExternalDeviceServiceIface(ctrl *gomock.Controller) *MockExternalDeviceServiceIface {
	mock := &MockExternalDeviceServiceIface{ctrl: ctrl}
	mock.recorder = &MockExternalDeviceServiceIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalDeviceServiceIface) EXPECT() *MockExternalDeviceServiceIfaceMockRecorder {
	return m.recorder
}

// AddCiscoAsa1000vResource mocks base method.
func (m *MockExternalDeviceServiceIface) AddCiscoAsa1000vResource(p *AddCiscoAsa1000vResourceParams) (*AddCiscoAsa1000vResourceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCiscoAsa1000vResource", p)
	ret0, _ := ret[0].(*AddCiscoAsa1000vResourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCiscoAsa1000vResource indicates an expected call of AddCiscoAsa1000vResource.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) AddCiscoAsa1000vResource(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCiscoAsa1000vResource", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).AddCiscoAsa1000vResource), p)
}

// AddCiscoVnmcResource mocks base method.
func (m *MockExternalDeviceServiceIface) AddCiscoVnmcResource(p *AddCiscoVnmcResourceParams) (*AddCiscoVnmcResourceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCiscoVnmcResource", p)
	ret0, _ := ret[0].(*AddCiscoVnmcResourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCiscoVnmcResource indicates an expected call of AddCiscoVnmcResource.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) AddCiscoVnmcResource(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCiscoVnmcResource", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).AddCiscoVnmcResource), p)
}

// DeleteCiscoAsa1000vResource mocks base method.
func (m *MockExternalDeviceServiceIface) DeleteCiscoAsa1000vResource(p *DeleteCiscoAsa1000vResourceParams) (*DeleteCiscoAsa1000vResourceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCiscoAsa1000vResource", p)
	ret0, _ := ret[0].(*DeleteCiscoAsa1000vResourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCiscoAsa1000vResource indicates an expected call of DeleteCiscoAsa1000vResource.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) DeleteCiscoAsa1000vResource(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCiscoAsa1000vResource", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).DeleteCiscoAsa1000vResource), p)
}

// DeleteCiscoNexusVSM mocks base method.
func (m *MockExternalDeviceServiceIface) DeleteCiscoNexusVSM(p *DeleteCiscoNexusVSMParams) (*DeleteCiscoNexusVSMResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCiscoNexusVSM", p)
	ret0, _ := ret[0].(*DeleteCiscoNexusVSMResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCiscoNexusVSM indicates an expected call of DeleteCiscoNexusVSM.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) DeleteCiscoNexusVSM(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCiscoNexusVSM", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).DeleteCiscoNexusVSM), p)
}

// DeleteCiscoVnmcResource mocks base method.
func (m *MockExternalDeviceServiceIface) DeleteCiscoVnmcResource(p *DeleteCiscoVnmcResourceParams) (*DeleteCiscoVnmcResourceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCiscoVnmcResource", p)
	ret0, _ := ret[0].(*DeleteCiscoVnmcResourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCiscoVnmcResource indicates an expected call of DeleteCiscoVnmcResource.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) DeleteCiscoVnmcResource(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCiscoVnmcResource", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).DeleteCiscoVnmcResource), p)
}

// DisableCiscoNexusVSM mocks base method.
func (m *MockExternalDeviceServiceIface) DisableCiscoNexusVSM(p *DisableCiscoNexusVSMParams) (*DisableCiscoNexusVSMResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableCiscoNexusVSM", p)
	ret0, _ := ret[0].(*DisableCiscoNexusVSMResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisableCiscoNexusVSM indicates an expected call of DisableCiscoNexusVSM.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) DisableCiscoNexusVSM(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableCiscoNexusVSM", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).DisableCiscoNexusVSM), p)
}

// EnableCiscoNexusVSM mocks base method.
func (m *MockExternalDeviceServiceIface) EnableCiscoNexusVSM(p *EnableCiscoNexusVSMParams) (*EnableCiscoNexusVSMResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableCiscoNexusVSM", p)
	ret0, _ := ret[0].(*EnableCiscoNexusVSMResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnableCiscoNexusVSM indicates an expected call of EnableCiscoNexusVSM.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) EnableCiscoNexusVSM(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableCiscoNexusVSM", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).EnableCiscoNexusVSM), p)
}

// ListCiscoAsa1000vResources mocks base method.
func (m *MockExternalDeviceServiceIface) ListCiscoAsa1000vResources(p *ListCiscoAsa1000vResourcesParams) (*ListCiscoAsa1000vResourcesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCiscoAsa1000vResources", p)
	ret0, _ := ret[0].(*ListCiscoAsa1000vResourcesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCiscoAsa1000vResources indicates an expected call of ListCiscoAsa1000vResources.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) ListCiscoAsa1000vResources(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCiscoAsa1000vResources", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).ListCiscoAsa1000vResources), p)
}

// ListCiscoNexusVSMs mocks base method.
func (m *MockExternalDeviceServiceIface) ListCiscoNexusVSMs(p *ListCiscoNexusVSMsParams) (*ListCiscoNexusVSMsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCiscoNexusVSMs", p)
	ret0, _ := ret[0].(*ListCiscoNexusVSMsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCiscoNexusVSMs indicates an expected call of ListCiscoNexusVSMs.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) ListCiscoNexusVSMs(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCiscoNexusVSMs", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).ListCiscoNexusVSMs), p)
}

// ListCiscoVnmcResources mocks base method.
func (m *MockExternalDeviceServiceIface) ListCiscoVnmcResources(p *ListCiscoVnmcResourcesParams) (*ListCiscoVnmcResourcesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCiscoVnmcResources", p)
	ret0, _ := ret[0].(*ListCiscoVnmcResourcesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCiscoVnmcResources indicates an expected call of ListCiscoVnmcResources.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) ListCiscoVnmcResources(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCiscoVnmcResources", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).ListCiscoVnmcResources), p)
}

// NewAddCiscoAsa1000vResourceParams mocks base method.
func (m *MockExternalDeviceServiceIface) NewAddCiscoAsa1000vResourceParams(clusterid, hostname, insideportprofile, physicalnetworkid string) *AddCiscoAsa1000vResourceParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAddCiscoAsa1000vResourceParams", clusterid, hostname, insideportprofile, physicalnetworkid)
	ret0, _ := ret[0].(*AddCiscoAsa1000vResourceParams)
	return ret0
}

// NewAddCiscoAsa1000vResourceParams indicates an expected call of NewAddCiscoAsa1000vResourceParams.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) NewAddCiscoAsa1000vResourceParams(clusterid, hostname, insideportprofile, physicalnetworkid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAddCiscoAsa1000vResourceParams", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).NewAddCiscoAsa1000vResourceParams), clusterid, hostname, insideportprofile, physicalnetworkid)
}

// NewAddCiscoVnmcResourceParams mocks base method.
func (m *MockExternalDeviceServiceIface) NewAddCiscoVnmcResourceParams(hostname, password, physicalnetworkid, username string) *AddCiscoVnmcResourceParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAddCiscoVnmcResourceParams", hostname, password, physicalnetworkid, username)
	ret0, _ := ret[0].(*AddCiscoVnmcResourceParams)
	return ret0
}

// NewAddCiscoVnmcResourceParams indicates an expected call of NewAddCiscoVnmcResourceParams.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) NewAddCiscoVnmcResourceParams(hostname, password, physicalnetworkid, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAddCiscoVnmcResourceParams", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).NewAddCiscoVnmcResourceParams), hostname, password, physicalnetworkid, username)
}

// NewDeleteCiscoAsa1000vResourceParams mocks base method.
func (m *MockExternalDeviceServiceIface) NewDeleteCiscoAsa1000vResourceParams(resourceid string) *DeleteCiscoAsa1000vResourceParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDeleteCiscoAsa1000vResourceParams", resourceid)
	ret0, _ := ret[0].(*DeleteCiscoAsa1000vResourceParams)
	return ret0
}

// NewDeleteCiscoAsa1000vResourceParams indicates an expected call of NewDeleteCiscoAsa1000vResourceParams.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) NewDeleteCiscoAsa1000vResourceParams(resourceid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDeleteCiscoAsa1000vResourceParams", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).NewDeleteCiscoAsa1000vResourceParams), resourceid)
}

// NewDeleteCiscoNexusVSMParams mocks base method.
func (m *MockExternalDeviceServiceIface) NewDeleteCiscoNexusVSMParams(id string) *DeleteCiscoNexusVSMParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDeleteCiscoNexusVSMParams", id)
	ret0, _ := ret[0].(*DeleteCiscoNexusVSMParams)
	return ret0
}

// NewDeleteCiscoNexusVSMParams indicates an expected call of NewDeleteCiscoNexusVSMParams.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) NewDeleteCiscoNexusVSMParams(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDeleteCiscoNexusVSMParams", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).NewDeleteCiscoNexusVSMParams), id)
}

// NewDeleteCiscoVnmcResourceParams mocks base method.
func (m *MockExternalDeviceServiceIface) NewDeleteCiscoVnmcResourceParams(resourceid string) *DeleteCiscoVnmcResourceParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDeleteCiscoVnmcResourceParams", resourceid)
	ret0, _ := ret[0].(*DeleteCiscoVnmcResourceParams)
	return ret0
}

// NewDeleteCiscoVnmcResourceParams indicates an expected call of NewDeleteCiscoVnmcResourceParams.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) NewDeleteCiscoVnmcResourceParams(resourceid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDeleteCiscoVnmcResourceParams", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).NewDeleteCiscoVnmcResourceParams), resourceid)
}

// NewDisableCiscoNexusVSMParams mocks base method.
func (m *MockExternalDeviceServiceIface) NewDisableCiscoNexusVSMParams(id string) *DisableCiscoNexusVSMParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDisableCiscoNexusVSMParams", id)
	ret0, _ := ret[0].(*DisableCiscoNexusVSMParams)
	return ret0
}

// NewDisableCiscoNexusVSMParams indicates an expected call of NewDisableCiscoNexusVSMParams.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) NewDisableCiscoNexusVSMParams(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDisableCiscoNexusVSMParams", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).NewDisableCiscoNexusVSMParams), id)
}

// NewEnableCiscoNexusVSMParams mocks base method.
func (m *MockExternalDeviceServiceIface) NewEnableCiscoNexusVSMParams(id string) *EnableCiscoNexusVSMParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewEnableCiscoNexusVSMParams", id)
	ret0, _ := ret[0].(*EnableCiscoNexusVSMParams)
	return ret0
}

// NewEnableCiscoNexusVSMParams indicates an expected call of NewEnableCiscoNexusVSMParams.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) NewEnableCiscoNexusVSMParams(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewEnableCiscoNexusVSMParams", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).NewEnableCiscoNexusVSMParams), id)
}

// NewListCiscoAsa1000vResourcesParams mocks base method.
func (m *MockExternalDeviceServiceIface) NewListCiscoAsa1000vResourcesParams() *ListCiscoAsa1000vResourcesParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListCiscoAsa1000vResourcesParams")
	ret0, _ := ret[0].(*ListCiscoAsa1000vResourcesParams)
	return ret0
}

// NewListCiscoAsa1000vResourcesParams indicates an expected call of NewListCiscoAsa1000vResourcesParams.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) NewListCiscoAsa1000vResourcesParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListCiscoAsa1000vResourcesParams", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).NewListCiscoAsa1000vResourcesParams))
}

// NewListCiscoNexusVSMsParams mocks base method.
func (m *MockExternalDeviceServiceIface) NewListCiscoNexusVSMsParams() *ListCiscoNexusVSMsParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListCiscoNexusVSMsParams")
	ret0, _ := ret[0].(*ListCiscoNexusVSMsParams)
	return ret0
}

// NewListCiscoNexusVSMsParams indicates an expected call of NewListCiscoNexusVSMsParams.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) NewListCiscoNexusVSMsParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListCiscoNexusVSMsParams", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).NewListCiscoNexusVSMsParams))
}

// NewListCiscoVnmcResourcesParams mocks base method.
func (m *MockExternalDeviceServiceIface) NewListCiscoVnmcResourcesParams() *ListCiscoVnmcResourcesParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListCiscoVnmcResourcesParams")
	ret0, _ := ret[0].(*ListCiscoVnmcResourcesParams)
	return ret0
}

// NewListCiscoVnmcResourcesParams indicates an expected call of NewListCiscoVnmcResourcesParams.
func (mr *MockExternalDeviceServiceIfaceMockRecorder) NewListCiscoVnmcResourcesParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListCiscoVnmcResourcesParams", reflect.TypeOf((*MockExternalDeviceServiceIface)(nil).NewListCiscoVnmcResourcesParams))
}
