//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: ./cloudstack/MetricsService.go

// Package cloudstack is a generated GoMock package.
package cloudstack

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricsServiceIface is a mock of MetricsServiceIface interface.
type MockMetricsServiceIface struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsServiceIfaceMockRecorder
}

// MockMetricsServiceIfaceMockRecorder is the mock recorder for MockMetricsServiceIface.
type MockMetricsServiceIfaceMockRecorder struct {
	mock *MockMetricsServiceIface
}

// NewMockMetricsServiceIface creates a new mock instance.
func NewMockMetricsServiceIface(ctrl *gomock.Controller) *MockMetricsServiceIface {
	mock := &MockMetricsServiceIface{ctrl: ctrl}
	mock.recorder = &MockMetricsServiceIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsServiceIface) EXPECT() *MockMetricsServiceIfaceMockRecorder {
	return m.recorder
}

// GetManagementServerByID mocks base method.
func (m *MockMetricsServiceIface) GetManagementServerByID(id string, opts ...OptionFunc) (*ManagementServer, int, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetManagementServerByID", varargs...)
	ret0, _ := ret[0].(*ManagementServer)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetManagementServerByID indicates an expected call of GetManagementServerByID.
func (mr *MockMetricsServiceIfaceMockRecorder) GetManagementServerByID(id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManagementServerByID", reflect.TypeOf((*MockMetricsServiceIface)(nil).GetManagementServerByID), varargs...)
}

// GetManagementServerByName mocks base method.
func (m *MockMetricsServiceIface) GetManagementServerByName(name string, opts ...OptionFunc) (*ManagementServer, int, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetManagementServerByName", varargs...)
	ret0, _ := ret[0].(*ManagementServer)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetManagementServerByName indicates an expected call of GetManagementServerByName.
func (mr *MockMetricsServiceIfaceMockRecorder) GetManagementServerByName(name interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManagementServerByName", reflect.TypeOf((*MockMetricsServiceIface)(nil).GetManagementServerByName), varargs...)
}

// GetManagementServerID mocks base method.
func (m *MockMetricsServiceIface) GetManagementServerID(name string, opts ...OptionFunc) (string, int, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetManagementServerID", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetManagementServerID indicates an expected call of GetManagementServerID.
func (mr *MockMetricsServiceIfaceMockRecorder) GetManagementServerID(name interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManagementServerID", reflect.TypeOf((*MockMetricsServiceIface)(nil).GetManagementServerID), varargs...)
}

// ListInfrastructure mocks base method.
func (m *MockMetricsServiceIface) ListInfrastructure(p *ListInfrastructureParams) (*ListInfrastructureResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInfrastructure", p)
	ret0, _ := ret[0].(*ListInfrastructureResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInfrastructure indicates an expected call of ListInfrastructure.
func (mr *MockMetricsServiceIfaceMockRecorder) ListInfrastructure(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInfrastructure", reflect.TypeOf((*MockMetricsServiceIface)(nil).ListInfrastructure), p)
}

// ListManagementServers mocks base method.
func (m *MockMetricsServiceIface) ListManagementServers(p *ListManagementServersParams) (*ListManagementServersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListManagementServers", p)
	ret0, _ := ret[0].(*ListManagementServersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListManagementServers indicates an expected call of ListManagementServers.
func (mr *MockMetricsServiceIfaceMockRecorder) ListManagementServers(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListManagementServers", reflect.TypeOf((*MockMetricsServiceIface)(nil).ListManagementServers), p)
}

// NewListInfrastructureParams mocks base method.
func (m *MockMetricsServiceIface) NewListInfrastructureParams() *ListInfrastructureParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListInfrastructureParams")
	ret0, _ := ret[0].(*ListInfrastructureParams)
	return ret0
}

// NewListInfrastructureParams indicates an expected call of NewListInfrastructureParams.
func (mr *MockMetricsServiceIfaceMockRecorder) NewListInfrastructureParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListInfrastructureParams", reflect.TypeOf((*MockMetricsServiceIface)(nil).NewListInfrastructureParams))
}

// NewListManagementServersParams mocks base method.
func (m *MockMetricsServiceIface) NewListManagementServersParams() *ListManagementServersParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListManagementServersParams")
	ret0, _ := ret[0].(*ListManagementServersParams)
	return ret0
}

// NewListManagementServersParams indicates an expected call of NewListManagementServersParams.
func (mr *MockMetricsServiceIfaceMockRecorder) NewListManagementServersParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListManagementServersParams", reflect.TypeOf((*MockMetricsServiceIface)(nil).NewListManagementServersParams))
}
