//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: ./cloudstack/PoolService.go

// Package cloudstack is a generated GoMock package.
package cloudstack

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPoolServiceIface is a mock of PoolServiceIface interface.
type MockPoolServiceIface struct {
	ctrl     *gomock.Controller
	recorder *MockPoolServiceIfaceMockRecorder
}

// MockPoolServiceIfaceMockRecorder is the mock recorder for MockPoolServiceIface.
type MockPoolServiceIfaceMockRecorder struct {
	mock *MockPoolServiceIface
}

// NewMockPoolServiceIface creates a new mock instance.
func NewMockPoolServiceIface(ctrl *gomock.Controller) *MockPoolServiceIface {
	mock := &MockPoolServiceIface{ctrl: ctrl}
	mock.recorder = &MockPoolServiceIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoolServiceIface) EXPECT() *MockPoolServiceIfaceMockRecorder {
	return m.recorder
}

// GetVsphereStoragePolicyCompatiblePoolID mocks base method.
func (m *MockPoolServiceIface) GetVsphereStoragePolicyCompatiblePoolID(keyword string, opts ...OptionFunc) (string, int, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{keyword}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetVsphereStoragePolicyCompatiblePoolID", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetVsphereStoragePolicyCompatiblePoolID indicates an expected call of GetVsphereStoragePolicyCompatiblePoolID.
func (mr *MockPoolServiceIfaceMockRecorder) GetVsphereStoragePolicyCompatiblePoolID(keyword interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{keyword}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVsphereStoragePolicyCompatiblePoolID", reflect.TypeOf((*MockPoolServiceIface)(nil).GetVsphereStoragePolicyCompatiblePoolID), varargs...)
}

// ListElastistorPool mocks base method.
func (m *MockPoolServiceIface) ListElastistorPool(p *ListElastistorPoolParams) (*ListElastistorPoolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListElastistorPool", p)
	ret0, _ := ret[0].(*ListElastistorPoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListElastistorPool indicates an expected call of ListElastistorPool.
func (mr *MockPoolServiceIfaceMockRecorder) ListElastistorPool(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListElastistorPool", reflect.TypeOf((*MockPoolServiceIface)(nil).ListElastistorPool), p)
}

// ListVsphereStoragePolicyCompatiblePools mocks base method.
func (m *MockPoolServiceIface) ListVsphereStoragePolicyCompatiblePools(p *ListVsphereStoragePolicyCompatiblePoolsParams) (*ListVsphereStoragePolicyCompatiblePoolsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVsphereStoragePolicyCompatiblePools", p)
	ret0, _ := ret[0].(*ListVsphereStoragePolicyCompatiblePoolsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVsphereStoragePolicyCompatiblePools indicates an expected call of ListVsphereStoragePolicyCompatiblePools.
func (mr *MockPoolServiceIfaceMockRecorder) ListVsphereStoragePolicyCompatiblePools(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVsphereStoragePolicyCompatiblePools", reflect.TypeOf((*MockPoolServiceIface)(nil).ListVsphereStoragePolicyCompatiblePools), p)
}

// NewListElastistorPoolParams mocks base method.
func (m *MockPoolServiceIface) NewListElastistorPoolParams() *ListElastistorPoolParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListElastistorPoolParams")
	ret0, _ := ret[0].(*ListElastistorPoolParams)
	return ret0
}

// NewListElastistorPoolParams indicates an expected call of NewListElastistorPoolParams.
func (mr *MockPoolServiceIfaceMockRecorder) NewListElastistorPoolParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListElastistorPoolParams", reflect.TypeOf((*MockPoolServiceIface)(nil).NewListElastistorPoolParams))
}

// NewListVsphereStoragePolicyCompatiblePoolsParams mocks base method.
func (m *MockPoolServiceIface) NewListVsphereStoragePolicyCompatiblePoolsParams() *ListVsphereStoragePolicyCompatiblePoolsParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListVsphereStoragePolicyCompatiblePoolsParams")
	ret0, _ := ret[0].(*ListVsphereStoragePolicyCompatiblePoolsParams)
	return ret0
}

// NewListVsphereStoragePolicyCompatiblePoolsParams indicates an expected call of NewListVsphereStoragePolicyCompatiblePoolsParams.
func (mr *MockPoolServiceIfaceMockRecorder) NewListVsphereStoragePolicyCompatiblePoolsParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListVsphereStoragePolicyCompatiblePoolsParams", reflect.TypeOf((*MockPoolServiceIface)(nil).NewListVsphereStoragePolicyCompatiblePoolsParams))
}
