//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: ./cloudstack/ShutdownService.go

// Package cloudstack is a generated GoMock package.
package cloudstack

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShutdownServiceIface is a mock of ShutdownServiceIface interface.
type MockShutdownServiceIface struct {
	ctrl     *gomock.Controller
	recorder *MockShutdownServiceIfaceMockRecorder
}

// MockShutdownServiceIfaceMockRecorder is the mock recorder for MockShutdownServiceIface.
type MockShutdownServiceIfaceMockRecorder struct {
	mock *MockShutdownServiceIface
}

// NewMockShutdownServiceIface creates a new mock instance.
func NewMockShutdownServiceIface(ctrl *gomock.Controller) *MockShutdownServiceIface {
	mock := &MockShutdownServiceIface{ctrl: ctrl}
	mock.recorder = &MockShutdownServiceIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShutdownServiceIface) EXPECT() *MockShutdownServiceIfaceMockRecorder {
	return m.recorder
}

// CancelShutdown mocks base method.
func (m *MockShutdownServiceIface) CancelShutdown(p *CancelShutdownParams) (*CancelShutdownResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelShutdown", p)
	ret0, _ := ret[0].(*CancelShutdownResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelShutdown indicates an expected call of CancelShutdown.
func (mr *MockShutdownServiceIfaceMockRecorder) CancelShutdown(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelShutdown", reflect.TypeOf((*MockShutdownServiceIface)(nil).CancelShutdown), p)
}

// NewCancelShutdownParams mocks base method.
func (m *MockShutdownServiceIface) NewCancelShutdownParams(managementserverid UUID) *CancelShutdownParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCancelShutdownParams", managementserverid)
	ret0, _ := ret[0].(*CancelShutdownParams)
	return ret0
}

// NewCancelShutdownParams indicates an expected call of NewCancelShutdownParams.
func (mr *MockShutdownServiceIfaceMockRecorder) NewCancelShutdownParams(managementserverid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCancelShutdownParams", reflect.TypeOf((*MockShutdownServiceIface)(nil).NewCancelShutdownParams), managementserverid)
}

// NewPrepareForShutdownParams mocks base method.
func (m *MockShutdownServiceIface) NewPrepareForShutdownParams(managementserverid UUID) *PrepareForShutdownParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewPrepareForShutdownParams", managementserverid)
	ret0, _ := ret[0].(*PrepareForShutdownParams)
	return ret0
}

// NewPrepareForShutdownParams indicates an expected call of NewPrepareForShutdownParams.
func (mr *MockShutdownServiceIfaceMockRecorder) NewPrepareForShutdownParams(managementserverid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPrepareForShutdownParams", reflect.TypeOf((*MockShutdownServiceIface)(nil).NewPrepareForShutdownParams), managementserverid)
}

// NewReadyForShutdownParams mocks base method.
func (m *MockShutdownServiceIface) NewReadyForShutdownParams() *ReadyForShutdownParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewReadyForShutdownParams")
	ret0, _ := ret[0].(*ReadyForShutdownParams)
	return ret0
}

// NewReadyForShutdownParams indicates an expected call of NewReadyForShutdownParams.
func (mr *MockShutdownServiceIfaceMockRecorder) NewReadyForShutdownParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewReadyForShutdownParams", reflect.TypeOf((*MockShutdownServiceIface)(nil).NewReadyForShutdownParams))
}

// NewTriggerShutdownParams mocks base method.
func (m *MockShutdownServiceIface) NewTriggerShutdownParams(managementserverid UUID) *TriggerShutdownParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTriggerShutdownParams", managementserverid)
	ret0, _ := ret[0].(*TriggerShutdownParams)
	return ret0
}

// NewTriggerShutdownParams indicates an expected call of NewTriggerShutdownParams.
func (mr *MockShutdownServiceIfaceMockRecorder) NewTriggerShutdownParams(managementserverid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTriggerShutdownParams", reflect.TypeOf((*MockShutdownServiceIface)(nil).NewTriggerShutdownParams), managementserverid)
}

// PrepareForShutdown mocks base method.
func (m *MockShutdownServiceIface) PrepareForShutdown(p *PrepareForShutdownParams) (*PrepareForShutdownResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareForShutdown", p)
	ret0, _ := ret[0].(*PrepareForShutdownResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareForShutdown indicates an expected call of PrepareForShutdown.
func (mr *MockShutdownServiceIfaceMockRecorder) PrepareForShutdown(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareForShutdown", reflect.TypeOf((*MockShutdownServiceIface)(nil).PrepareForShutdown), p)
}

// ReadyForShutdown mocks base method.
func (m *MockShutdownServiceIface) ReadyForShutdown(p *ReadyForShutdownParams) (*ReadyForShutdownResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadyForShutdown", p)
	ret0, _ := ret[0].(*ReadyForShutdownResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadyForShutdown indicates an expected call of ReadyForShutdown.
func (mr *MockShutdownServiceIfaceMockRecorder) ReadyForShutdown(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadyForShutdown", reflect.TypeOf((*MockShutdownServiceIface)(nil).ReadyForShutdown), p)
}

// TriggerShutdown mocks base method.
func (m *MockShutdownServiceIface) TriggerShutdown(p *TriggerShutdownParams) (*TriggerShutdownResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerShutdown", p)
	ret0, _ := ret[0].(*TriggerShutdownResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerShutdown indicates an expected call of TriggerShutdown.
func (mr *MockShutdownServiceIfaceMockRecorder) TriggerShutdown(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerShutdown", reflect.TypeOf((*MockShutdownServiceIface)(nil).TriggerShutdown), p)
}
