//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: ./cloudstack/SiocService.go

// Package cloudstack is a generated GoMock package.
package cloudstack

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSiocServiceIface is a mock of SiocServiceIface interface.
type MockSiocServiceIface struct {
	ctrl     *gomock.Controller
	recorder *MockSiocServiceIfaceMockRecorder
}

// MockSiocServiceIfaceMockRecorder is the mock recorder for MockSiocServiceIface.
type MockSiocServiceIfaceMockRecorder struct {
	mock *MockSiocServiceIface
}

// NewMockSiocServiceIface creates a new mock instance.
func NewMockSiocServiceIface(ctrl *gomock.Controller) *MockSiocServiceIface {
	mock := &MockSiocServiceIface{ctrl: ctrl}
	mock.recorder = &MockSiocServiceIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSiocServiceIface) EXPECT() *MockSiocServiceIfaceMockRecorder {
	return m.recorder
}

// NewUpdateSiocInfoParams mocks base method.
func (m *MockSiocServiceIface) NewUpdateSiocInfoParams(iopsnotifythreshold, limitiopspergb, sharespergb int, storageid, zoneid string) *UpdateSiocInfoParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUpdateSiocInfoParams", iopsnotifythreshold, limitiopspergb, sharespergb, storageid, zoneid)
	ret0, _ := ret[0].(*UpdateSiocInfoParams)
	return ret0
}

// NewUpdateSiocInfoParams indicates an expected call of NewUpdateSiocInfoParams.
func (mr *MockSiocServiceIfaceMockRecorder) NewUpdateSiocInfoParams(iopsnotifythreshold, limitiopspergb, sharespergb, storageid, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUpdateSiocInfoParams", reflect.TypeOf((*MockSiocServiceIface)(nil).NewUpdateSiocInfoParams), iopsnotifythreshold, limitiopspergb, sharespergb, storageid, zoneid)
}

// UpdateSiocInfo mocks base method.
func (m *MockSiocServiceIface) UpdateSiocInfo(p *UpdateSiocInfoParams) (*UpdateSiocInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSiocInfo", p)
	ret0, _ := ret[0].(*UpdateSiocInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSiocInfo indicates an expected call of UpdateSiocInfo.
func (mr *MockSiocServiceIfaceMockRecorder) UpdateSiocInfo(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSiocInfo", reflect.TypeOf((*MockSiocServiceIface)(nil).UpdateSiocInfo), p)
}
