//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: ./cloudstack/TungstenService.go

// Package cloudstack is a generated GoMock package.
package cloudstack

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTungstenServiceIface is a mock of TungstenServiceIface interface.
type MockTungstenServiceIface struct {
	ctrl     *gomock.Controller
	recorder *MockTungstenServiceIfaceMockRecorder
}

// MockTungstenServiceIfaceMockRecorder is the mock recorder for MockTungstenServiceIface.
type MockTungstenServiceIfaceMockRecorder struct {
	mock *MockTungstenServiceIface
}

// NewMockTungstenServiceIface creates a new mock instance.
func NewMockTungstenServiceIface(ctrl *gomock.Controller) *MockTungstenServiceIface {
	mock := &MockTungstenServiceIface{ctrl: ctrl}
	mock.recorder = &MockTungstenServiceIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTungstenServiceIface) EXPECT() *MockTungstenServiceIfaceMockRecorder {
	return m.recorder
}

// AddTungstenFabricPolicyRule mocks base method.
func (m *MockTungstenServiceIface) AddTungstenFabricPolicyRule(p *AddTungstenFabricPolicyRuleParams) (*AddTungstenFabricPolicyRuleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTungstenFabricPolicyRule", p)
	ret0, _ := ret[0].(*AddTungstenFabricPolicyRuleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTungstenFabricPolicyRule indicates an expected call of AddTungstenFabricPolicyRule.
func (mr *MockTungstenServiceIfaceMockRecorder) AddTungstenFabricPolicyRule(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTungstenFabricPolicyRule", reflect.TypeOf((*MockTungstenServiceIface)(nil).AddTungstenFabricPolicyRule), p)
}

// ApplyTungstenFabricPolicy mocks base method.
func (m *MockTungstenServiceIface) ApplyTungstenFabricPolicy(p *ApplyTungstenFabricPolicyParams) (*ApplyTungstenFabricPolicyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyTungstenFabricPolicy", p)
	ret0, _ := ret[0].(*ApplyTungstenFabricPolicyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyTungstenFabricPolicy indicates an expected call of ApplyTungstenFabricPolicy.
func (mr *MockTungstenServiceIfaceMockRecorder) ApplyTungstenFabricPolicy(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyTungstenFabricPolicy", reflect.TypeOf((*MockTungstenServiceIface)(nil).ApplyTungstenFabricPolicy), p)
}

// ApplyTungstenFabricTag mocks base method.
func (m *MockTungstenServiceIface) ApplyTungstenFabricTag(p *ApplyTungstenFabricTagParams) (*ApplyTungstenFabricTagResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyTungstenFabricTag", p)
	ret0, _ := ret[0].(*ApplyTungstenFabricTagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyTungstenFabricTag indicates an expected call of ApplyTungstenFabricTag.
func (mr *MockTungstenServiceIfaceMockRecorder) ApplyTungstenFabricTag(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyTungstenFabricTag", reflect.TypeOf((*MockTungstenServiceIface)(nil).ApplyTungstenFabricTag), p)
}

// ConfigTungstenFabricService mocks base method.
func (m *MockTungstenServiceIface) ConfigTungstenFabricService(p *ConfigTungstenFabricServiceParams) (*ConfigTungstenFabricServiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigTungstenFabricService", p)
	ret0, _ := ret[0].(*ConfigTungstenFabricServiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfigTungstenFabricService indicates an expected call of ConfigTungstenFabricService.
func (mr *MockTungstenServiceIfaceMockRecorder) ConfigTungstenFabricService(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigTungstenFabricService", reflect.TypeOf((*MockTungstenServiceIface)(nil).ConfigTungstenFabricService), p)
}

// CreateTungstenFabricAddressGroup mocks base method.
func (m *MockTungstenServiceIface) CreateTungstenFabricAddressGroup(p *CreateTungstenFabricAddressGroupParams) (*CreateTungstenFabricAddressGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTungstenFabricAddressGroup", p)
	ret0, _ := ret[0].(*CreateTungstenFabricAddressGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTungstenFabricAddressGroup indicates an expected call of CreateTungstenFabricAddressGroup.
func (mr *MockTungstenServiceIfaceMockRecorder) CreateTungstenFabricAddressGroup(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTungstenFabricAddressGroup", reflect.TypeOf((*MockTungstenServiceIface)(nil).CreateTungstenFabricAddressGroup), p)
}

// CreateTungstenFabricApplicationPolicySet mocks base method.
func (m *MockTungstenServiceIface) CreateTungstenFabricApplicationPolicySet(p *CreateTungstenFabricApplicationPolicySetParams) (*CreateTungstenFabricApplicationPolicySetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTungstenFabricApplicationPolicySet", p)
	ret0, _ := ret[0].(*CreateTungstenFabricApplicationPolicySetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTungstenFabricApplicationPolicySet indicates an expected call of CreateTungstenFabricApplicationPolicySet.
func (mr *MockTungstenServiceIfaceMockRecorder) CreateTungstenFabricApplicationPolicySet(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTungstenFabricApplicationPolicySet", reflect.TypeOf((*MockTungstenServiceIface)(nil).CreateTungstenFabricApplicationPolicySet), p)
}

// CreateTungstenFabricPolicy mocks base method.
func (m *MockTungstenServiceIface) CreateTungstenFabricPolicy(p *CreateTungstenFabricPolicyParams) (*CreateTungstenFabricPolicyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTungstenFabricPolicy", p)
	ret0, _ := ret[0].(*CreateTungstenFabricPolicyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTungstenFabricPolicy indicates an expected call of CreateTungstenFabricPolicy.
func (mr *MockTungstenServiceIfaceMockRecorder) CreateTungstenFabricPolicy(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTungstenFabricPolicy", reflect.TypeOf((*MockTungstenServiceIface)(nil).CreateTungstenFabricPolicy), p)
}

// CreateTungstenFabricProvider mocks base method.
func (m *MockTungstenServiceIface) CreateTungstenFabricProvider(p *CreateTungstenFabricProviderParams) (*CreateTungstenFabricProviderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTungstenFabricProvider", p)
	ret0, _ := ret[0].(*CreateTungstenFabricProviderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTungstenFabricProvider indicates an expected call of CreateTungstenFabricProvider.
func (mr *MockTungstenServiceIfaceMockRecorder) CreateTungstenFabricProvider(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTungstenFabricProvider", reflect.TypeOf((*MockTungstenServiceIface)(nil).CreateTungstenFabricProvider), p)
}

// CreateTungstenFabricServiceGroup mocks base method.
func (m *MockTungstenServiceIface) CreateTungstenFabricServiceGroup(p *CreateTungstenFabricServiceGroupParams) (*CreateTungstenFabricServiceGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTungstenFabricServiceGroup", p)
	ret0, _ := ret[0].(*CreateTungstenFabricServiceGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTungstenFabricServiceGroup indicates an expected call of CreateTungstenFabricServiceGroup.
func (mr *MockTungstenServiceIfaceMockRecorder) CreateTungstenFabricServiceGroup(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTungstenFabricServiceGroup", reflect.TypeOf((*MockTungstenServiceIface)(nil).CreateTungstenFabricServiceGroup), p)
}

// CreateTungstenFabricTag mocks base method.
func (m *MockTungstenServiceIface) CreateTungstenFabricTag(p *CreateTungstenFabricTagParams) (*CreateTungstenFabricTagResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTungstenFabricTag", p)
	ret0, _ := ret[0].(*CreateTungstenFabricTagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTungstenFabricTag indicates an expected call of CreateTungstenFabricTag.
func (mr *MockTungstenServiceIfaceMockRecorder) CreateTungstenFabricTag(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTungstenFabricTag", reflect.TypeOf((*MockTungstenServiceIface)(nil).CreateTungstenFabricTag), p)
}

// CreateTungstenFabricTagType mocks base method.
func (m *MockTungstenServiceIface) CreateTungstenFabricTagType(p *CreateTungstenFabricTagTypeParams) (*CreateTungstenFabricTagTypeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTungstenFabricTagType", p)
	ret0, _ := ret[0].(*CreateTungstenFabricTagTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTungstenFabricTagType indicates an expected call of CreateTungstenFabricTagType.
func (mr *MockTungstenServiceIfaceMockRecorder) CreateTungstenFabricTagType(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTungstenFabricTagType", reflect.TypeOf((*MockTungstenServiceIface)(nil).CreateTungstenFabricTagType), p)
}

// DeleteTungstenFabricAddressGroup mocks base method.
func (m *MockTungstenServiceIface) DeleteTungstenFabricAddressGroup(p *DeleteTungstenFabricAddressGroupParams) (*DeleteTungstenFabricAddressGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTungstenFabricAddressGroup", p)
	ret0, _ := ret[0].(*DeleteTungstenFabricAddressGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTungstenFabricAddressGroup indicates an expected call of DeleteTungstenFabricAddressGroup.
func (mr *MockTungstenServiceIfaceMockRecorder) DeleteTungstenFabricAddressGroup(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTungstenFabricAddressGroup", reflect.TypeOf((*MockTungstenServiceIface)(nil).DeleteTungstenFabricAddressGroup), p)
}

// DeleteTungstenFabricApplicationPolicySet mocks base method.
func (m *MockTungstenServiceIface) DeleteTungstenFabricApplicationPolicySet(p *DeleteTungstenFabricApplicationPolicySetParams) (*DeleteTungstenFabricApplicationPolicySetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTungstenFabricApplicationPolicySet", p)
	ret0, _ := ret[0].(*DeleteTungstenFabricApplicationPolicySetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTungstenFabricApplicationPolicySet indicates an expected call of DeleteTungstenFabricApplicationPolicySet.
func (mr *MockTungstenServiceIfaceMockRecorder) DeleteTungstenFabricApplicationPolicySet(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTungstenFabricApplicationPolicySet", reflect.TypeOf((*MockTungstenServiceIface)(nil).DeleteTungstenFabricApplicationPolicySet), p)
}

// DeleteTungstenFabricPolicy mocks base method.
func (m *MockTungstenServiceIface) DeleteTungstenFabricPolicy(p *DeleteTungstenFabricPolicyParams) (*DeleteTungstenFabricPolicyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTungstenFabricPolicy", p)
	ret0, _ := ret[0].(*DeleteTungstenFabricPolicyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTungstenFabricPolicy indicates an expected call of DeleteTungstenFabricPolicy.
func (mr *MockTungstenServiceIfaceMockRecorder) DeleteTungstenFabricPolicy(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTungstenFabricPolicy", reflect.TypeOf((*MockTungstenServiceIface)(nil).DeleteTungstenFabricPolicy), p)
}

// DeleteTungstenFabricServiceGroup mocks base method.
func (m *MockTungstenServiceIface) DeleteTungstenFabricServiceGroup(p *DeleteTungstenFabricServiceGroupParams) (*DeleteTungstenFabricServiceGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTungstenFabricServiceGroup", p)
	ret0, _ := ret[0].(*DeleteTungstenFabricServiceGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTungstenFabricServiceGroup indicates an expected call of DeleteTungstenFabricServiceGroup.
func (mr *MockTungstenServiceIfaceMockRecorder) DeleteTungstenFabricServiceGroup(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTungstenFabricServiceGroup", reflect.TypeOf((*MockTungstenServiceIface)(nil).DeleteTungstenFabricServiceGroup), p)
}

// DeleteTungstenFabricTag mocks base method.
func (m *MockTungstenServiceIface) DeleteTungstenFabricTag(p *DeleteTungstenFabricTagParams) (*DeleteTungstenFabricTagResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTungstenFabricTag", p)
	ret0, _ := ret[0].(*DeleteTungstenFabricTagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTungstenFabricTag indicates an expected call of DeleteTungstenFabricTag.
func (mr *MockTungstenServiceIfaceMockRecorder) DeleteTungstenFabricTag(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTungstenFabricTag", reflect.TypeOf((*MockTungstenServiceIface)(nil).DeleteTungstenFabricTag), p)
}

// DeleteTungstenFabricTagType mocks base method.
func (m *MockTungstenServiceIface) DeleteTungstenFabricTagType(p *DeleteTungstenFabricTagTypeParams) (*DeleteTungstenFabricTagTypeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTungstenFabricTagType", p)
	ret0, _ := ret[0].(*DeleteTungstenFabricTagTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTungstenFabricTagType indicates an expected call of DeleteTungstenFabricTagType.
func (mr *MockTungstenServiceIfaceMockRecorder) DeleteTungstenFabricTagType(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTungstenFabricTagType", reflect.TypeOf((*MockTungstenServiceIface)(nil).DeleteTungstenFabricTagType), p)
}

// ListTungstenFabricAddressGroup mocks base method.
func (m *MockTungstenServiceIface) ListTungstenFabricAddressGroup(p *ListTungstenFabricAddressGroupParams) (*ListTungstenFabricAddressGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTungstenFabricAddressGroup", p)
	ret0, _ := ret[0].(*ListTungstenFabricAddressGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTungstenFabricAddressGroup indicates an expected call of ListTungstenFabricAddressGroup.
func (mr *MockTungstenServiceIfaceMockRecorder) ListTungstenFabricAddressGroup(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTungstenFabricAddressGroup", reflect.TypeOf((*MockTungstenServiceIface)(nil).ListTungstenFabricAddressGroup), p)
}

// ListTungstenFabricApplicationPolicySet mocks base method.
func (m *MockTungstenServiceIface) ListTungstenFabricApplicationPolicySet(p *ListTungstenFabricApplicationPolicySetParams) (*ListTungstenFabricApplicationPolicySetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTungstenFabricApplicationPolicySet", p)
	ret0, _ := ret[0].(*ListTungstenFabricApplicationPolicySetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTungstenFabricApplicationPolicySet indicates an expected call of ListTungstenFabricApplicationPolicySet.
func (mr *MockTungstenServiceIfaceMockRecorder) ListTungstenFabricApplicationPolicySet(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTungstenFabricApplicationPolicySet", reflect.TypeOf((*MockTungstenServiceIface)(nil).ListTungstenFabricApplicationPolicySet), p)
}

// ListTungstenFabricLBHealthMonitor mocks base method.
func (m *MockTungstenServiceIface) ListTungstenFabricLBHealthMonitor(p *ListTungstenFabricLBHealthMonitorParams) (*ListTungstenFabricLBHealthMonitorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTungstenFabricLBHealthMonitor", p)
	ret0, _ := ret[0].(*ListTungstenFabricLBHealthMonitorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTungstenFabricLBHealthMonitor indicates an expected call of ListTungstenFabricLBHealthMonitor.
func (mr *MockTungstenServiceIfaceMockRecorder) ListTungstenFabricLBHealthMonitor(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTungstenFabricLBHealthMonitor", reflect.TypeOf((*MockTungstenServiceIface)(nil).ListTungstenFabricLBHealthMonitor), p)
}

// ListTungstenFabricNic mocks base method.
func (m *MockTungstenServiceIface) ListTungstenFabricNic(p *ListTungstenFabricNicParams) (*ListTungstenFabricNicResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTungstenFabricNic", p)
	ret0, _ := ret[0].(*ListTungstenFabricNicResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTungstenFabricNic indicates an expected call of ListTungstenFabricNic.
func (mr *MockTungstenServiceIfaceMockRecorder) ListTungstenFabricNic(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTungstenFabricNic", reflect.TypeOf((*MockTungstenServiceIface)(nil).ListTungstenFabricNic), p)
}

// ListTungstenFabricPolicy mocks base method.
func (m *MockTungstenServiceIface) ListTungstenFabricPolicy(p *ListTungstenFabricPolicyParams) (*ListTungstenFabricPolicyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTungstenFabricPolicy", p)
	ret0, _ := ret[0].(*ListTungstenFabricPolicyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTungstenFabricPolicy indicates an expected call of ListTungstenFabricPolicy.
func (mr *MockTungstenServiceIfaceMockRecorder) ListTungstenFabricPolicy(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTungstenFabricPolicy", reflect.TypeOf((*MockTungstenServiceIface)(nil).ListTungstenFabricPolicy), p)
}

// ListTungstenFabricPolicyRule mocks base method.
func (m *MockTungstenServiceIface) ListTungstenFabricPolicyRule(p *ListTungstenFabricPolicyRuleParams) (*ListTungstenFabricPolicyRuleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTungstenFabricPolicyRule", p)
	ret0, _ := ret[0].(*ListTungstenFabricPolicyRuleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTungstenFabricPolicyRule indicates an expected call of ListTungstenFabricPolicyRule.
func (mr *MockTungstenServiceIfaceMockRecorder) ListTungstenFabricPolicyRule(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTungstenFabricPolicyRule", reflect.TypeOf((*MockTungstenServiceIface)(nil).ListTungstenFabricPolicyRule), p)
}

// ListTungstenFabricProviders mocks base method.
func (m *MockTungstenServiceIface) ListTungstenFabricProviders(p *ListTungstenFabricProvidersParams) (*ListTungstenFabricProvidersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTungstenFabricProviders", p)
	ret0, _ := ret[0].(*ListTungstenFabricProvidersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTungstenFabricProviders indicates an expected call of ListTungstenFabricProviders.
func (mr *MockTungstenServiceIfaceMockRecorder) ListTungstenFabricProviders(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTungstenFabricProviders", reflect.TypeOf((*MockTungstenServiceIface)(nil).ListTungstenFabricProviders), p)
}

// ListTungstenFabricServiceGroup mocks base method.
func (m *MockTungstenServiceIface) ListTungstenFabricServiceGroup(p *ListTungstenFabricServiceGroupParams) (*ListTungstenFabricServiceGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTungstenFabricServiceGroup", p)
	ret0, _ := ret[0].(*ListTungstenFabricServiceGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTungstenFabricServiceGroup indicates an expected call of ListTungstenFabricServiceGroup.
func (mr *MockTungstenServiceIfaceMockRecorder) ListTungstenFabricServiceGroup(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTungstenFabricServiceGroup", reflect.TypeOf((*MockTungstenServiceIface)(nil).ListTungstenFabricServiceGroup), p)
}

// ListTungstenFabricTag mocks base method.
func (m *MockTungstenServiceIface) ListTungstenFabricTag(p *ListTungstenFabricTagParams) (*ListTungstenFabricTagResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTungstenFabricTag", p)
	ret0, _ := ret[0].(*ListTungstenFabricTagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTungstenFabricTag indicates an expected call of ListTungstenFabricTag.
func (mr *MockTungstenServiceIfaceMockRecorder) ListTungstenFabricTag(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTungstenFabricTag", reflect.TypeOf((*MockTungstenServiceIface)(nil).ListTungstenFabricTag), p)
}

// ListTungstenFabricTagType mocks base method.
func (m *MockTungstenServiceIface) ListTungstenFabricTagType(p *ListTungstenFabricTagTypeParams) (*ListTungstenFabricTagTypeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTungstenFabricTagType", p)
	ret0, _ := ret[0].(*ListTungstenFabricTagTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTungstenFabricTagType indicates an expected call of ListTungstenFabricTagType.
func (mr *MockTungstenServiceIfaceMockRecorder) ListTungstenFabricTagType(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTungstenFabricTagType", reflect.TypeOf((*MockTungstenServiceIface)(nil).ListTungstenFabricTagType), p)
}

// ListTungstenFabricVm mocks base method.
func (m *MockTungstenServiceIface) ListTungstenFabricVm(p *ListTungstenFabricVmParams) (*ListTungstenFabricVmResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTungstenFabricVm", p)
	ret0, _ := ret[0].(*ListTungstenFabricVmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTungstenFabricVm indicates an expected call of ListTungstenFabricVm.
func (mr *MockTungstenServiceIfaceMockRecorder) ListTungstenFabricVm(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTungstenFabricVm", reflect.TypeOf((*MockTungstenServiceIface)(nil).ListTungstenFabricVm), p)
}

// NewAddTungstenFabricPolicyRuleParams mocks base method.
func (m *MockTungstenServiceIface) NewAddTungstenFabricPolicyRuleParams(action string, destendport int, destipprefix string, destipprefixlen int, destnetwork string, deststartport int, direction, policyuuid, protocol string, srcendport int, srcipprefix string, srcipprefixlen int, srcnetwork string, srcstartport int, zoneid string) *AddTungstenFabricPolicyRuleParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAddTungstenFabricPolicyRuleParams", action, destendport, destipprefix, destipprefixlen, destnetwork, deststartport, direction, policyuuid, protocol, srcendport, srcipprefix, srcipprefixlen, srcnetwork, srcstartport, zoneid)
	ret0, _ := ret[0].(*AddTungstenFabricPolicyRuleParams)
	return ret0
}

// NewAddTungstenFabricPolicyRuleParams indicates an expected call of NewAddTungstenFabricPolicyRuleParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewAddTungstenFabricPolicyRuleParams(action, destendport, destipprefix, destipprefixlen, destnetwork, deststartport, direction, policyuuid, protocol, srcendport, srcipprefix, srcipprefixlen, srcnetwork, srcstartport, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAddTungstenFabricPolicyRuleParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewAddTungstenFabricPolicyRuleParams), action, destendport, destipprefix, destipprefixlen, destnetwork, deststartport, direction, policyuuid, protocol, srcendport, srcipprefix, srcipprefixlen, srcnetwork, srcstartport, zoneid)
}

// NewApplyTungstenFabricPolicyParams mocks base method.
func (m *MockTungstenServiceIface) NewApplyTungstenFabricPolicyParams(majorsequence, minorsequence int, networkuuid, policyuuid, zoneid string) *ApplyTungstenFabricPolicyParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewApplyTungstenFabricPolicyParams", majorsequence, minorsequence, networkuuid, policyuuid, zoneid)
	ret0, _ := ret[0].(*ApplyTungstenFabricPolicyParams)
	return ret0
}

// NewApplyTungstenFabricPolicyParams indicates an expected call of NewApplyTungstenFabricPolicyParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewApplyTungstenFabricPolicyParams(majorsequence, minorsequence, networkuuid, policyuuid, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewApplyTungstenFabricPolicyParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewApplyTungstenFabricPolicyParams), majorsequence, minorsequence, networkuuid, policyuuid, zoneid)
}

// NewApplyTungstenFabricTagParams mocks base method.
func (m *MockTungstenServiceIface) NewApplyTungstenFabricTagParams(taguuid, zoneid string) *ApplyTungstenFabricTagParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewApplyTungstenFabricTagParams", taguuid, zoneid)
	ret0, _ := ret[0].(*ApplyTungstenFabricTagParams)
	return ret0
}

// NewApplyTungstenFabricTagParams indicates an expected call of NewApplyTungstenFabricTagParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewApplyTungstenFabricTagParams(taguuid, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewApplyTungstenFabricTagParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewApplyTungstenFabricTagParams), taguuid, zoneid)
}

// NewConfigTungstenFabricServiceParams mocks base method.
func (m *MockTungstenServiceIface) NewConfigTungstenFabricServiceParams(physicalnetworkid, zoneid string) *ConfigTungstenFabricServiceParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewConfigTungstenFabricServiceParams", physicalnetworkid, zoneid)
	ret0, _ := ret[0].(*ConfigTungstenFabricServiceParams)
	return ret0
}

// NewConfigTungstenFabricServiceParams indicates an expected call of NewConfigTungstenFabricServiceParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewConfigTungstenFabricServiceParams(physicalnetworkid, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConfigTungstenFabricServiceParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewConfigTungstenFabricServiceParams), physicalnetworkid, zoneid)
}

// NewCreateTungstenFabricAddressGroupParams mocks base method.
func (m *MockTungstenServiceIface) NewCreateTungstenFabricAddressGroupParams(ipprefix string, ipprefixlen int, name, zoneid string) *CreateTungstenFabricAddressGroupParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCreateTungstenFabricAddressGroupParams", ipprefix, ipprefixlen, name, zoneid)
	ret0, _ := ret[0].(*CreateTungstenFabricAddressGroupParams)
	return ret0
}

// NewCreateTungstenFabricAddressGroupParams indicates an expected call of NewCreateTungstenFabricAddressGroupParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewCreateTungstenFabricAddressGroupParams(ipprefix, ipprefixlen, name, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCreateTungstenFabricAddressGroupParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewCreateTungstenFabricAddressGroupParams), ipprefix, ipprefixlen, name, zoneid)
}

// NewCreateTungstenFabricApplicationPolicySetParams mocks base method.
func (m *MockTungstenServiceIface) NewCreateTungstenFabricApplicationPolicySetParams(name, zoneid string) *CreateTungstenFabricApplicationPolicySetParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCreateTungstenFabricApplicationPolicySetParams", name, zoneid)
	ret0, _ := ret[0].(*CreateTungstenFabricApplicationPolicySetParams)
	return ret0
}

// NewCreateTungstenFabricApplicationPolicySetParams indicates an expected call of NewCreateTungstenFabricApplicationPolicySetParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewCreateTungstenFabricApplicationPolicySetParams(name, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCreateTungstenFabricApplicationPolicySetParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewCreateTungstenFabricApplicationPolicySetParams), name, zoneid)
}

// NewCreateTungstenFabricPolicyParams mocks base method.
func (m *MockTungstenServiceIface) NewCreateTungstenFabricPolicyParams(name, zoneid string) *CreateTungstenFabricPolicyParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCreateTungstenFabricPolicyParams", name, zoneid)
	ret0, _ := ret[0].(*CreateTungstenFabricPolicyParams)
	return ret0
}

// NewCreateTungstenFabricPolicyParams indicates an expected call of NewCreateTungstenFabricPolicyParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewCreateTungstenFabricPolicyParams(name, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCreateTungstenFabricPolicyParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewCreateTungstenFabricPolicyParams), name, zoneid)
}

// NewCreateTungstenFabricProviderParams mocks base method.
func (m *MockTungstenServiceIface) NewCreateTungstenFabricProviderParams(name, tungstengateway, tungstenproviderhostname, zoneid string) *CreateTungstenFabricProviderParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCreateTungstenFabricProviderParams", name, tungstengateway, tungstenproviderhostname, zoneid)
	ret0, _ := ret[0].(*CreateTungstenFabricProviderParams)
	return ret0
}

// NewCreateTungstenFabricProviderParams indicates an expected call of NewCreateTungstenFabricProviderParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewCreateTungstenFabricProviderParams(name, tungstengateway, tungstenproviderhostname, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCreateTungstenFabricProviderParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewCreateTungstenFabricProviderParams), name, tungstengateway, tungstenproviderhostname, zoneid)
}

// NewCreateTungstenFabricServiceGroupParams mocks base method.
func (m *MockTungstenServiceIface) NewCreateTungstenFabricServiceGroupParams(endport int, name, protocol string, startport int, zoneid string) *CreateTungstenFabricServiceGroupParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCreateTungstenFabricServiceGroupParams", endport, name, protocol, startport, zoneid)
	ret0, _ := ret[0].(*CreateTungstenFabricServiceGroupParams)
	return ret0
}

// NewCreateTungstenFabricServiceGroupParams indicates an expected call of NewCreateTungstenFabricServiceGroupParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewCreateTungstenFabricServiceGroupParams(endport, name, protocol, startport, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCreateTungstenFabricServiceGroupParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewCreateTungstenFabricServiceGroupParams), endport, name, protocol, startport, zoneid)
}

// NewCreateTungstenFabricTagParams mocks base method.
func (m *MockTungstenServiceIface) NewCreateTungstenFabricTagParams(tagtype, tagvalue, zoneid string) *CreateTungstenFabricTagParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCreateTungstenFabricTagParams", tagtype, tagvalue, zoneid)
	ret0, _ := ret[0].(*CreateTungstenFabricTagParams)
	return ret0
}

// NewCreateTungstenFabricTagParams indicates an expected call of NewCreateTungstenFabricTagParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewCreateTungstenFabricTagParams(tagtype, tagvalue, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCreateTungstenFabricTagParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewCreateTungstenFabricTagParams), tagtype, tagvalue, zoneid)
}

// NewCreateTungstenFabricTagTypeParams mocks base method.
func (m *MockTungstenServiceIface) NewCreateTungstenFabricTagTypeParams(name, zoneid string) *CreateTungstenFabricTagTypeParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCreateTungstenFabricTagTypeParams", name, zoneid)
	ret0, _ := ret[0].(*CreateTungstenFabricTagTypeParams)
	return ret0
}

// NewCreateTungstenFabricTagTypeParams indicates an expected call of NewCreateTungstenFabricTagTypeParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewCreateTungstenFabricTagTypeParams(name, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCreateTungstenFabricTagTypeParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewCreateTungstenFabricTagTypeParams), name, zoneid)
}

// NewDeleteTungstenFabricAddressGroupParams mocks base method.
func (m *MockTungstenServiceIface) NewDeleteTungstenFabricAddressGroupParams(addressgroupuuid, zoneid string) *DeleteTungstenFabricAddressGroupParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDeleteTungstenFabricAddressGroupParams", addressgroupuuid, zoneid)
	ret0, _ := ret[0].(*DeleteTungstenFabricAddressGroupParams)
	return ret0
}

// NewDeleteTungstenFabricAddressGroupParams indicates an expected call of NewDeleteTungstenFabricAddressGroupParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewDeleteTungstenFabricAddressGroupParams(addressgroupuuid, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDeleteTungstenFabricAddressGroupParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewDeleteTungstenFabricAddressGroupParams), addressgroupuuid, zoneid)
}

// NewDeleteTungstenFabricApplicationPolicySetParams mocks base method.
func (m *MockTungstenServiceIface) NewDeleteTungstenFabricApplicationPolicySetParams(applicationpolicysetuuid, zoneid string) *DeleteTungstenFabricApplicationPolicySetParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDeleteTungstenFabricApplicationPolicySetParams", applicationpolicysetuuid, zoneid)
	ret0, _ := ret[0].(*DeleteTungstenFabricApplicationPolicySetParams)
	return ret0
}

// NewDeleteTungstenFabricApplicationPolicySetParams indicates an expected call of NewDeleteTungstenFabricApplicationPolicySetParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewDeleteTungstenFabricApplicationPolicySetParams(applicationpolicysetuuid, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDeleteTungstenFabricApplicationPolicySetParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewDeleteTungstenFabricApplicationPolicySetParams), applicationpolicysetuuid, zoneid)
}

// NewDeleteTungstenFabricPolicyParams mocks base method.
func (m *MockTungstenServiceIface) NewDeleteTungstenFabricPolicyParams(policyuuid, zoneid string) *DeleteTungstenFabricPolicyParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDeleteTungstenFabricPolicyParams", policyuuid, zoneid)
	ret0, _ := ret[0].(*DeleteTungstenFabricPolicyParams)
	return ret0
}

// NewDeleteTungstenFabricPolicyParams indicates an expected call of NewDeleteTungstenFabricPolicyParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewDeleteTungstenFabricPolicyParams(policyuuid, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDeleteTungstenFabricPolicyParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewDeleteTungstenFabricPolicyParams), policyuuid, zoneid)
}

// NewDeleteTungstenFabricServiceGroupParams mocks base method.
func (m *MockTungstenServiceIface) NewDeleteTungstenFabricServiceGroupParams(servicegroupuuid, zoneid string) *DeleteTungstenFabricServiceGroupParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDeleteTungstenFabricServiceGroupParams", servicegroupuuid, zoneid)
	ret0, _ := ret[0].(*DeleteTungstenFabricServiceGroupParams)
	return ret0
}

// NewDeleteTungstenFabricServiceGroupParams indicates an expected call of NewDeleteTungstenFabricServiceGroupParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewDeleteTungstenFabricServiceGroupParams(servicegroupuuid, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDeleteTungstenFabricServiceGroupParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewDeleteTungstenFabricServiceGroupParams), servicegroupuuid, zoneid)
}

// NewDeleteTungstenFabricTagParams mocks base method.
func (m *MockTungstenServiceIface) NewDeleteTungstenFabricTagParams(taguuid, zoneid string) *DeleteTungstenFabricTagParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDeleteTungstenFabricTagParams", taguuid, zoneid)
	ret0, _ := ret[0].(*DeleteTungstenFabricTagParams)
	return ret0
}

// NewDeleteTungstenFabricTagParams indicates an expected call of NewDeleteTungstenFabricTagParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewDeleteTungstenFabricTagParams(taguuid, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDeleteTungstenFabricTagParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewDeleteTungstenFabricTagParams), taguuid, zoneid)
}

// NewDeleteTungstenFabricTagTypeParams mocks base method.
func (m *MockTungstenServiceIface) NewDeleteTungstenFabricTagTypeParams(tagtypeuuid, zoneid string) *DeleteTungstenFabricTagTypeParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDeleteTungstenFabricTagTypeParams", tagtypeuuid, zoneid)
	ret0, _ := ret[0].(*DeleteTungstenFabricTagTypeParams)
	return ret0
}

// NewDeleteTungstenFabricTagTypeParams indicates an expected call of NewDeleteTungstenFabricTagTypeParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewDeleteTungstenFabricTagTypeParams(tagtypeuuid, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDeleteTungstenFabricTagTypeParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewDeleteTungstenFabricTagTypeParams), tagtypeuuid, zoneid)
}

// NewListTungstenFabricAddressGroupParams mocks base method.
func (m *MockTungstenServiceIface) NewListTungstenFabricAddressGroupParams() *ListTungstenFabricAddressGroupParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListTungstenFabricAddressGroupParams")
	ret0, _ := ret[0].(*ListTungstenFabricAddressGroupParams)
	return ret0
}

// NewListTungstenFabricAddressGroupParams indicates an expected call of NewListTungstenFabricAddressGroupParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewListTungstenFabricAddressGroupParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListTungstenFabricAddressGroupParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewListTungstenFabricAddressGroupParams))
}

// NewListTungstenFabricApplicationPolicySetParams mocks base method.
func (m *MockTungstenServiceIface) NewListTungstenFabricApplicationPolicySetParams() *ListTungstenFabricApplicationPolicySetParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListTungstenFabricApplicationPolicySetParams")
	ret0, _ := ret[0].(*ListTungstenFabricApplicationPolicySetParams)
	return ret0
}

// NewListTungstenFabricApplicationPolicySetParams indicates an expected call of NewListTungstenFabricApplicationPolicySetParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewListTungstenFabricApplicationPolicySetParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListTungstenFabricApplicationPolicySetParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewListTungstenFabricApplicationPolicySetParams))
}

// NewListTungstenFabricLBHealthMonitorParams mocks base method.
func (m *MockTungstenServiceIface) NewListTungstenFabricLBHealthMonitorParams(lbruleid string) *ListTungstenFabricLBHealthMonitorParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListTungstenFabricLBHealthMonitorParams", lbruleid)
	ret0, _ := ret[0].(*ListTungstenFabricLBHealthMonitorParams)
	return ret0
}

// NewListTungstenFabricLBHealthMonitorParams indicates an expected call of NewListTungstenFabricLBHealthMonitorParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewListTungstenFabricLBHealthMonitorParams(lbruleid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListTungstenFabricLBHealthMonitorParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewListTungstenFabricLBHealthMonitorParams), lbruleid)
}

// NewListTungstenFabricNicParams mocks base method.
func (m *MockTungstenServiceIface) NewListTungstenFabricNicParams() *ListTungstenFabricNicParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListTungstenFabricNicParams")
	ret0, _ := ret[0].(*ListTungstenFabricNicParams)
	return ret0
}

// NewListTungstenFabricNicParams indicates an expected call of NewListTungstenFabricNicParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewListTungstenFabricNicParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListTungstenFabricNicParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewListTungstenFabricNicParams))
}

// NewListTungstenFabricPolicyParams mocks base method.
func (m *MockTungstenServiceIface) NewListTungstenFabricPolicyParams() *ListTungstenFabricPolicyParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListTungstenFabricPolicyParams")
	ret0, _ := ret[0].(*ListTungstenFabricPolicyParams)
	return ret0
}

// NewListTungstenFabricPolicyParams indicates an expected call of NewListTungstenFabricPolicyParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewListTungstenFabricPolicyParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListTungstenFabricPolicyParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewListTungstenFabricPolicyParams))
}

// NewListTungstenFabricPolicyRuleParams mocks base method.
func (m *MockTungstenServiceIface) NewListTungstenFabricPolicyRuleParams(policyuuid string) *ListTungstenFabricPolicyRuleParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListTungstenFabricPolicyRuleParams", policyuuid)
	ret0, _ := ret[0].(*ListTungstenFabricPolicyRuleParams)
	return ret0
}

// NewListTungstenFabricPolicyRuleParams indicates an expected call of NewListTungstenFabricPolicyRuleParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewListTungstenFabricPolicyRuleParams(policyuuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListTungstenFabricPolicyRuleParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewListTungstenFabricPolicyRuleParams), policyuuid)
}

// NewListTungstenFabricProvidersParams mocks base method.
func (m *MockTungstenServiceIface) NewListTungstenFabricProvidersParams() *ListTungstenFabricProvidersParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListTungstenFabricProvidersParams")
	ret0, _ := ret[0].(*ListTungstenFabricProvidersParams)
	return ret0
}

// NewListTungstenFabricProvidersParams indicates an expected call of NewListTungstenFabricProvidersParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewListTungstenFabricProvidersParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListTungstenFabricProvidersParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewListTungstenFabricProvidersParams))
}

// NewListTungstenFabricServiceGroupParams mocks base method.
func (m *MockTungstenServiceIface) NewListTungstenFabricServiceGroupParams() *ListTungstenFabricServiceGroupParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListTungstenFabricServiceGroupParams")
	ret0, _ := ret[0].(*ListTungstenFabricServiceGroupParams)
	return ret0
}

// NewListTungstenFabricServiceGroupParams indicates an expected call of NewListTungstenFabricServiceGroupParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewListTungstenFabricServiceGroupParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListTungstenFabricServiceGroupParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewListTungstenFabricServiceGroupParams))
}

// NewListTungstenFabricTagParams mocks base method.
func (m *MockTungstenServiceIface) NewListTungstenFabricTagParams() *ListTungstenFabricTagParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListTungstenFabricTagParams")
	ret0, _ := ret[0].(*ListTungstenFabricTagParams)
	return ret0
}

// NewListTungstenFabricTagParams indicates an expected call of NewListTungstenFabricTagParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewListTungstenFabricTagParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListTungstenFabricTagParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewListTungstenFabricTagParams))
}

// NewListTungstenFabricTagTypeParams mocks base method.
func (m *MockTungstenServiceIface) NewListTungstenFabricTagTypeParams() *ListTungstenFabricTagTypeParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListTungstenFabricTagTypeParams")
	ret0, _ := ret[0].(*ListTungstenFabricTagTypeParams)
	return ret0
}

// NewListTungstenFabricTagTypeParams indicates an expected call of NewListTungstenFabricTagTypeParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewListTungstenFabricTagTypeParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListTungstenFabricTagTypeParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewListTungstenFabricTagTypeParams))
}

// NewListTungstenFabricVmParams mocks base method.
func (m *MockTungstenServiceIface) NewListTungstenFabricVmParams() *ListTungstenFabricVmParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListTungstenFabricVmParams")
	ret0, _ := ret[0].(*ListTungstenFabricVmParams)
	return ret0
}

// NewListTungstenFabricVmParams indicates an expected call of NewListTungstenFabricVmParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewListTungstenFabricVmParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListTungstenFabricVmParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewListTungstenFabricVmParams))
}

// NewRemoveTungstenFabricPolicyParams mocks base method.
func (m *MockTungstenServiceIface) NewRemoveTungstenFabricPolicyParams(networkuuid, policyuuid, zoneid string) *RemoveTungstenFabricPolicyParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRemoveTungstenFabricPolicyParams", networkuuid, policyuuid, zoneid)
	ret0, _ := ret[0].(*RemoveTungstenFabricPolicyParams)
	return ret0
}

// NewRemoveTungstenFabricPolicyParams indicates an expected call of NewRemoveTungstenFabricPolicyParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewRemoveTungstenFabricPolicyParams(networkuuid, policyuuid, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRemoveTungstenFabricPolicyParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewRemoveTungstenFabricPolicyParams), networkuuid, policyuuid, zoneid)
}

// NewRemoveTungstenFabricPolicyRuleParams mocks base method.
func (m *MockTungstenServiceIface) NewRemoveTungstenFabricPolicyRuleParams(policyuuid, ruleuuid, zoneid string) *RemoveTungstenFabricPolicyRuleParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRemoveTungstenFabricPolicyRuleParams", policyuuid, ruleuuid, zoneid)
	ret0, _ := ret[0].(*RemoveTungstenFabricPolicyRuleParams)
	return ret0
}

// NewRemoveTungstenFabricPolicyRuleParams indicates an expected call of NewRemoveTungstenFabricPolicyRuleParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewRemoveTungstenFabricPolicyRuleParams(policyuuid, ruleuuid, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRemoveTungstenFabricPolicyRuleParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewRemoveTungstenFabricPolicyRuleParams), policyuuid, ruleuuid, zoneid)
}

// NewRemoveTungstenFabricTagParams mocks base method.
func (m *MockTungstenServiceIface) NewRemoveTungstenFabricTagParams(taguuid, zoneid string) *RemoveTungstenFabricTagParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRemoveTungstenFabricTagParams", taguuid, zoneid)
	ret0, _ := ret[0].(*RemoveTungstenFabricTagParams)
	return ret0
}

// NewRemoveTungstenFabricTagParams indicates an expected call of NewRemoveTungstenFabricTagParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewRemoveTungstenFabricTagParams(taguuid, zoneid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRemoveTungstenFabricTagParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewRemoveTungstenFabricTagParams), taguuid, zoneid)
}

// NewSynchronizeTungstenFabricDataParams mocks base method.
func (m *MockTungstenServiceIface) NewSynchronizeTungstenFabricDataParams(id string) *SynchronizeTungstenFabricDataParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSynchronizeTungstenFabricDataParams", id)
	ret0, _ := ret[0].(*SynchronizeTungstenFabricDataParams)
	return ret0
}

// NewSynchronizeTungstenFabricDataParams indicates an expected call of NewSynchronizeTungstenFabricDataParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewSynchronizeTungstenFabricDataParams(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSynchronizeTungstenFabricDataParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewSynchronizeTungstenFabricDataParams), id)
}

// NewUpdateTungstenFabricLBHealthMonitorParams mocks base method.
func (m *MockTungstenServiceIface) NewUpdateTungstenFabricLBHealthMonitorParams(interval int, lbruleid string, retry, timeout int, tungstenType string) *UpdateTungstenFabricLBHealthMonitorParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUpdateTungstenFabricLBHealthMonitorParams", interval, lbruleid, retry, timeout, tungstenType)
	ret0, _ := ret[0].(*UpdateTungstenFabricLBHealthMonitorParams)
	return ret0
}

// NewUpdateTungstenFabricLBHealthMonitorParams indicates an expected call of NewUpdateTungstenFabricLBHealthMonitorParams.
func (mr *MockTungstenServiceIfaceMockRecorder) NewUpdateTungstenFabricLBHealthMonitorParams(interval, lbruleid, retry, timeout, tungstenType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUpdateTungstenFabricLBHealthMonitorParams", reflect.TypeOf((*MockTungstenServiceIface)(nil).NewUpdateTungstenFabricLBHealthMonitorParams), interval, lbruleid, retry, timeout, tungstenType)
}

// RemoveTungstenFabricPolicy mocks base method.
func (m *MockTungstenServiceIface) RemoveTungstenFabricPolicy(p *RemoveTungstenFabricPolicyParams) (*RemoveTungstenFabricPolicyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTungstenFabricPolicy", p)
	ret0, _ := ret[0].(*RemoveTungstenFabricPolicyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveTungstenFabricPolicy indicates an expected call of RemoveTungstenFabricPolicy.
func (mr *MockTungstenServiceIfaceMockRecorder) RemoveTungstenFabricPolicy(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTungstenFabricPolicy", reflect.TypeOf((*MockTungstenServiceIface)(nil).RemoveTungstenFabricPolicy), p)
}

// RemoveTungstenFabricPolicyRule mocks base method.
func (m *MockTungstenServiceIface) RemoveTungstenFabricPolicyRule(p *RemoveTungstenFabricPolicyRuleParams) (*RemoveTungstenFabricPolicyRuleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTungstenFabricPolicyRule", p)
	ret0, _ := ret[0].(*RemoveTungstenFabricPolicyRuleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveTungstenFabricPolicyRule indicates an expected call of RemoveTungstenFabricPolicyRule.
func (mr *MockTungstenServiceIfaceMockRecorder) RemoveTungstenFabricPolicyRule(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTungstenFabricPolicyRule", reflect.TypeOf((*MockTungstenServiceIface)(nil).RemoveTungstenFabricPolicyRule), p)
}

// RemoveTungstenFabricTag mocks base method.
func (m *MockTungstenServiceIface) RemoveTungstenFabricTag(p *RemoveTungstenFabricTagParams) (*RemoveTungstenFabricTagResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTungstenFabricTag", p)
	ret0, _ := ret[0].(*RemoveTungstenFabricTagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveTungstenFabricTag indicates an expected call of RemoveTungstenFabricTag.
func (mr *MockTungstenServiceIfaceMockRecorder) RemoveTungstenFabricTag(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTungstenFabricTag", reflect.TypeOf((*MockTungstenServiceIface)(nil).RemoveTungstenFabricTag), p)
}

// SynchronizeTungstenFabricData mocks base method.
func (m *MockTungstenServiceIface) SynchronizeTungstenFabricData(p *SynchronizeTungstenFabricDataParams) (*SynchronizeTungstenFabricDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SynchronizeTungstenFabricData", p)
	ret0, _ := ret[0].(*SynchronizeTungstenFabricDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SynchronizeTungstenFabricData indicates an expected call of SynchronizeTungstenFabricData.
func (mr *MockTungstenServiceIfaceMockRecorder) SynchronizeTungstenFabricData(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SynchronizeTungstenFabricData", reflect.TypeOf((*MockTungstenServiceIface)(nil).SynchronizeTungstenFabricData), p)
}

// UpdateTungstenFabricLBHealthMonitor mocks base method.
func (m *MockTungstenServiceIface) UpdateTungstenFabricLBHealthMonitor(p *UpdateTungstenFabricLBHealthMonitorParams) (*UpdateTungstenFabricLBHealthMonitorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTungstenFabricLBHealthMonitor", p)
	ret0, _ := ret[0].(*UpdateTungstenFabricLBHealthMonitorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTungstenFabricLBHealthMonitor indicates an expected call of UpdateTungstenFabricLBHealthMonitor.
func (mr *MockTungstenServiceIfaceMockRecorder) UpdateTungstenFabricLBHealthMonitor(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTungstenFabricLBHealthMonitor", reflect.TypeOf((*MockTungstenServiceIface)(nil).UpdateTungstenFabricLBHealthMonitor), p)
}
