//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: ./cloudstack/VSphereStoragePoliciesService.go

// Package cloudstack is a generated GoMock package.
package cloudstack

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockVSphereStoragePoliciesServiceIface is a mock of VSphereStoragePoliciesServiceIface interface.
type MockVSphereStoragePoliciesServiceIface struct {
	ctrl     *gomock.Controller
	recorder *MockVSphereStoragePoliciesServiceIfaceMockRecorder
}

// MockVSphereStoragePoliciesServiceIfaceMockRecorder is the mock recorder for MockVSphereStoragePoliciesServiceIface.
type MockVSphereStoragePoliciesServiceIfaceMockRecorder struct {
	mock *MockVSphereStoragePoliciesServiceIface
}

// NewMockVSphereStoragePoliciesServiceIface creates a new mock instance.
func NewMockVSphereStoragePoliciesServiceIface(ctrl *gomock.Controller) *MockVSphereStoragePoliciesServiceIface {
	mock := &MockVSphereStoragePoliciesServiceIface{ctrl: ctrl}
	mock.recorder = &MockVSphereStoragePoliciesServiceIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVSphereStoragePoliciesServiceIface) EXPECT() *MockVSphereStoragePoliciesServiceIfaceMockRecorder {
	return m.recorder
}

// ImportVsphereStoragePolicies mocks base method.
func (m *MockVSphereStoragePoliciesServiceIface) ImportVsphereStoragePolicies(p *ImportVsphereStoragePoliciesParams) (*ImportVsphereStoragePoliciesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportVsphereStoragePolicies", p)
	ret0, _ := ret[0].(*ImportVsphereStoragePoliciesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportVsphereStoragePolicies indicates an expected call of ImportVsphereStoragePolicies.
func (mr *MockVSphereStoragePoliciesServiceIfaceMockRecorder) ImportVsphereStoragePolicies(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportVsphereStoragePolicies", reflect.TypeOf((*MockVSphereStoragePoliciesServiceIface)(nil).ImportVsphereStoragePolicies), p)
}

// ListVsphereStoragePolicies mocks base method.
func (m *MockVSphereStoragePoliciesServiceIface) ListVsphereStoragePolicies(p *ListVsphereStoragePoliciesParams) (*ListVsphereStoragePoliciesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVsphereStoragePolicies", p)
	ret0, _ := ret[0].(*ListVsphereStoragePoliciesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVsphereStoragePolicies indicates an expected call of ListVsphereStoragePolicies.
func (mr *MockVSphereStoragePoliciesServiceIfaceMockRecorder) ListVsphereStoragePolicies(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVsphereStoragePolicies", reflect.TypeOf((*MockVSphereStoragePoliciesServiceIface)(nil).ListVsphereStoragePolicies), p)
}

// NewImportVsphereStoragePoliciesParams mocks base method.
func (m *MockVSphereStoragePoliciesServiceIface) NewImportVsphereStoragePoliciesParams() *ImportVsphereStoragePoliciesParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewImportVsphereStoragePoliciesParams")
	ret0, _ := ret[0].(*ImportVsphereStoragePoliciesParams)
	return ret0
}

// NewImportVsphereStoragePoliciesParams indicates an expected call of NewImportVsphereStoragePoliciesParams.
func (mr *MockVSphereStoragePoliciesServiceIfaceMockRecorder) NewImportVsphereStoragePoliciesParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewImportVsphereStoragePoliciesParams", reflect.TypeOf((*MockVSphereStoragePoliciesServiceIface)(nil).NewImportVsphereStoragePoliciesParams))
}

// NewListVsphereStoragePoliciesParams mocks base method.
func (m *MockVSphereStoragePoliciesServiceIface) NewListVsphereStoragePoliciesParams() *ListVsphereStoragePoliciesParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListVsphereStoragePoliciesParams")
	ret0, _ := ret[0].(*ListVsphereStoragePoliciesParams)
	return ret0
}

// NewListVsphereStoragePoliciesParams indicates an expected call of NewListVsphereStoragePoliciesParams.
func (mr *MockVSphereStoragePoliciesServiceIfaceMockRecorder) NewListVsphereStoragePoliciesParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListVsphereStoragePoliciesParams", reflect.TypeOf((*MockVSphereStoragePoliciesServiceIface)(nil).NewListVsphereStoragePoliciesParams))
}
